### ISSUE TITLE
Practica seguimiento y control

### ISSUE THREAD

**Issue by kirus21** [SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-dream-team1#1]
[Practica seguimiento-control.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-dream-team1/files/10189633/Practica.seguimiento-control.pdf)

**Comment by uzias10** [comment]
48/50 buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
